{{- $fullName := include "world-of-reos-web.fullname" . -}}
  {{- $ingressPath := .Values.web.ingress.path -}}
  {{- $port := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ .Values.web.name }}
    chart: {{ template "world-of-reos-web.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: {{ .Values.web.ingress.issuer }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 5m
spec:
  {{- if .Values.web.ingress.tls }}
  tls:
    {{- range .Values.web.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
      {{- end }}
      {{- end }}
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
      {{- end }}

