replicaCount: 1

web:
  name: world-of-reos-web
  image:
    repository: r.cfcr.io/fusionhs/world-of-reos/world-of-reos-web
    tag: master
    pullPolicy: Always
  ingress:
    issuer: letsencrypt-prod
    path: /
    hosts:
      - worldofreos.com
      - worldofreos.fusionhs.com
    tls:
      - secretName: worldofreos-tls
        hosts:
          - worldofreos.com
      - secretName: worldofreos-fusionhs-tls
        hosts:
          - worldofreos.fusionhs.com
pullSecret: codefresh-generated-r.cfcr.io-fusionhs-docker-reg-world-of-reos
service:
  type: ClusterIP
  port: 8080


